name: upload-lambda-action
description: Reusable action to build and upload Lambda to S3

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build ${{ env.LAMBDA_NAME }} zip
      shell: bash
      run: |
        cd $LAMBDA_NAME
        make
        mkdir -p zip/
        mv *.zip zip/

    - name: Extract branch name
      shell: bash
      id: extract_branch
      run: echo "branch=$(echo "${GITHUB_REF_NAME/\//-}")" >> $GITHUB_OUTPUT

    - name: Upload to S3 (official AWS sync)
      uses: aws-actions/s3-sync@f2701ae75301088999913e7d758ec7d4dfbaf8d3 # v1.2.1
      with:
        bucket: mattermost-cloud-lambdas-${{ env.ENVIRONMENT }}
        source-dir: ${{ env.LAMBDA_NAME }}/zip
        destination-dir: ${{ env.LAMBDA_NAME }}/${{ steps.extract_branch.outputs.branch }}/${{ github.run_number }}

