name: upload-lambda-action
description: Reusable action to build and upload a single Lambda to S3

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709

    - name: Build ${{ env.LAMBDA_NAME }} zip
      shell: bash
      run: |
        cd $LAMBDA_NAME
        make
        mkdir -p zip/
        mv *.zip zip/

    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: |
        echo "branch=$(echo \"${GITHUB_REF_NAME//\//-}\")" >> $GITHUB_OUTPUT

    - name: Sync Lambda ZIP to S3
      shell: bash
      run: |
        aws s3 sync \
          "${LAMBDA_NAME}/zip" \
          "s3://mattermost-cloud-lambdas-${ENVIRONMENT}/${LAMBDA_NAME}/${{ steps.extract_branch.outputs.branch }}/${GITHUB_RUN_NUMBER}"
