name: upload-lambda-action
description: Reusable action to upload Lambdas to S3

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build ${{ env.LAMBDA_NAME }} zip
      shell: bash
      run: |
        cd $LAMBDA_NAME
        make
        mkdir -p zip/
        mv *.zip zip/

    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo "${GITHUB_REF_NAME/\//-}")" >>$GITHUB_OUTPUT # replace / with -
      id: extract_branch

    - name: Upload test version to S3
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: 'mattermost-cloud-lambdas-${{ env.ENVIRONMENT }}'
        AWS_ACCESS_KEY_ID: '${{ env.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ env.AWS_SECRET_ACCESS_KEY }}'
        SOURCE_DIR: '${{ env.LAMBDA_NAME }}/zip'
        DEST_DIR: '${{ env.LAMBDA_NAME }}/${{ steps.extract_branch.outputs.branch }}/${{ github.run_number }}'
