# Docs: https://golangci-lint.run/usage/configuration/#config-file

# This version should be updated when updating golangci-lint version
version: 2

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  govet:
    enable:
      - shadow
    disable:
      - fieldalignment
      - atomicalign

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive          # replacement for golint
    - gocyclo         # cyclomatic complexity
    - misspell        # spelling errors
    - predeclared     # check for shadowing predeclared identifiers
    - unconvert       # unnecessary conversions
