name: Upload account-alerts to S3

on:
  push:
    branches:
      - main
      - feat/CLD-5088

jobs:
  core-upload:
    name: Upload account-alerts core function to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build account-alerts zip
        shell: bash
        run: |
          cd account-alerts
          make
          mkdir -p zip/
          mv main.zip zip/

      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: mattermost-cloud-lambdas
          AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDAS_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDAS_AWS_SECRET_ACCESS_KEY}}
          SOURCE_DIR: 'account-alerts/zip'      # optional: defaults to entire repository
          DEST_DIR: 'core/account-alerts/${{ github.ref_name }}/${{ github.run_number }}' # optional: defaults to root of bucket
