name: Upload lambdas to S3 for Core

on:
  push:
    branches:
      - main

jobs:
  upload-core-lambdas:
    uses: ./.github/workflows/upload-lambdas-template.yml
    with:
      environment: core
    secrets:
      aws_access_key_id: ${{ secrets.CORE_LAMBDA_AWS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.CORE_LAMBDA_AWS_SECRET_ACCESS_KEY }}
