name: Upload Lambdas to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environments:
        description: "Comma-separated environments to deploy (e.g. dev,test,prod)"
        required: false
        default: "dev,test,core,shared-services,data-engineering,prod"

jobs:
  upload-lambdas:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, test, core, shared-services, data-engineering, prod]

    if: |
      github.event_name == 'push' ||
      contains(github.event.inputs.environments, matrix.environment)

    steps:
      - name: Map environment to account ID
        id: map
        run: |
          case "${{ matrix.environment }}" in
            dev) echo "aws_account_id=${{ secrets.DEV_AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT ;;
            test) echo "aws_account_id=${{ secrets.TEST_AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT ;;
            core) echo "aws_account_id=${{ secrets.CORE_AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT ;;
            shared-services) echo "aws_account_id=${{ secrets.SHARED_AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT ;;
            data-engineering) echo "aws_account_id=${{ secrets.DATA_ENGINEERING_AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT ;;
            prod) echo "aws_account_id=${{ secrets.PROD_AWS_ACCOUNT_ID }}" >> $GITHUB_OUTPUT ;;
            *) echo "Unknown environment: ${{ matrix.environment }}" && exit 1 ;;
          esac

      - name: Call Upload Lambdas Reusable Workflow
        uses: ./.github/workflows/upload-lambdas-template.yml
        with:
          environment: ${{ matrix.environment }}
        secrets:
          aws_account_id: ${{ steps.map.outputs.aws_account_id }}

