name: Upload Lambdas to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environments:
        description: "Comma-separated environments to deploy (e.g. dev,test,prod)"
        required: false
        default: "dev,test,core,shared-services,data-engineering,prod"

jobs:
  upload-lambdas:
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, test, core, shared-services, data-engineering, prod]

    if: |
      github.event_name == 'push' ||
      contains(github.event.inputs.environments, matrix.environment)

    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Call Upload Lambdas Reusable Workflow
        uses: ./.github/workflows/upload-lambdas-template.yml
        with:
          environment: ${{ matrix.environment }}
        secrets:
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
