name: Upload Lambdas to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environments:
        description: "Comma-separated environments to deploy (e.g. dev,test,prod)"
        required: false
        default: "dev,test,core,shared-services,data-engineering,prod"

jobs:
  determine-environments:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.set-environments.outputs.environments }}
    steps:
      - id: set-environments
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo 'environments=["dev", "test", "core", "shared-services", "data-engineering", "prod"]' >> $GITHUB_OUTPUT
          else
            # Convert comma-separated string to JSON array
            IFS=',' read -ra ENV_ARRAY <<< "${{ github.event.inputs.environments }}"
            JSON_ARRAY=$(printf '"%s",' "${ENV_ARRAY[@]}" | sed 's/,$//')
            echo "environments=[$JSON_ARRAY]" >> $GITHUB_OUTPUT
          fi

  upload-lambdas:
    needs: determine-environments
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.determine-environments.outputs.environments) }}
    uses: ./.github/workflows/upload-lambdas-template.yml
    with:
      environment: ${{ matrix.environment }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

