name: Upload lambdas to S3 for prod

on:
  push:
    branches:
      - main

jobs:
  upload-prod-lambdas:
    uses: ./.github/workflows/upload-lambdas-template.yml
    with:
      environment: prod
    secrets:
      aws_key_id: ${{ secrets.PROD_LAMBDA_AWS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.PROD_LAMBDA_AWS_SECRET_ACCESS_KEY }}
