name: Upload lambdas to S3 for shared-services

on:
  push:
    branches:
      - main

jobs:
  upload-shared-services-lambdas:
    uses: ./.github/workflows/upload-lambdas-template.yml
    with:
      environment: shared-services
    secrets:
      aws_access_key_id: ${{ secrets.SHARED_SERVICES_LAMBDA_AWS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.SHARED_SERVICES_LAMBDA_AWS_SECRET_ACCESS_KEY }}
