name: Upload lambdas to S3 for test

on:
  push:
    branches:
      - main

jobs:
  upload-test-lambdas:
    uses: ./.github/workflows/upload-lambdas-template.yml
    with:
      environment: test
    secrets:
      aws_access_key_id: ${{ secrets.TEST_LAMBDA_AWS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.TEST_LAMBDA_AWS_SECRET_ACCESS_KEY }}
